- pkg/operators/nids/us.go
- pkg/operators/operators.go
- pkg/operators/validate_nid.go
- pkg/parser/parser.go
- pkg/parser/parser_test.go
- test/data/operators/nids.json
> add nids support and more tests

- actions/ctl.go
- seclang/directives.go
- transaction.go
* body buffers now restores original buffers
* Fixed .data path
> important fixes

- transformations/remove_whitespace.go
> fix(removewhitespace): move to golang funcs

- loggers/formats.go
> Before submitting check if what you want to add to `coraza-waf` list meets [quality standards](https://github.com/jptosso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!
> fix for auditlog

- loggers/formats.go
- waf.go
> Before submitting check if what you want to add to `coraza-waf` list meets [quality standards](https://github.com/jptosso/coraza-waf/blob/master/CONTRIBUTING.md#quality-standards) before sending pull request. Thanks!
> Fix for some config does not work

- rule.go
- seclang/directives.go
- seclang/rule_parser.go
- seclang/rules_test.go
- testdata/engine/default_actions.yaml
- testdata/engine/directives.yaml
- transaction.go
> fix for #172

- seclang/rule_parser.go
- testdata/engine/match.yaml
> feat(operator): support SecRule "! ^some" as a valid @rx negation

- README.md
- Changed project status to lab
- Add pre-commit instructions
- Add troubleshooting for the repo name change
- Other minor changes
> README: add owasp status, pre-commit and new org

- bodyprocessors/json.go
- bodyprocessors/json_test.go
> fix: support array format for parsing json data in the body processor

- loggers/concurrent_writer.go
- loggers/concurrent_writer_test.go
- loggers/logger.go
- loggers/serial_writer.go
- loggers/serial_writer_test.go
- seclang/directives.go
- seclang/directives_test.go
- seclang/parser.go
- seclang/rule_parser.go
- types/waf.go
- waf.go
> feat: use DirectiveOptions instead of waf.Config to share variables across directives

- .github/workflows/codeql-analysis.yml
- .github/workflows/go-ftw.yml
- .github/workflows/lint.yml
- .github/workflows/regression.yml
> fix(actions): Remove branch patterns from action scope

- operators/rx.go
- operators/rx_test.go
- seclang/rules_test.go
> fix(@rx): add @rx captured data into Tx variable

- rule.go
- rule_match.go
- seclang/rules_test.go
- testdata/engine/chains.yaml
- testdata/engine/default_actions.yaml
- testdata/engine/json.yaml
- testdata/engine/variables.yaml
- testing/engine.go
- transaction.go
> Rule matches optimization: Fix for #183

- waf.go
> fix: remove unused code

- operators/rx.go
- seclang/rules_test.go
> fix(rx): support non utf-8 format data matching

- seclang/parser.go
- seclang/parser_test.go
- testdata/includes/parent.conf
- testdata/includes/postdirectives.conf
- testdata/includes/subinclude/rules1.conf
- testdata/includes/subinclude/rules2.conf
- testdata/includes/subinclude/rules3.conf
Fix Include Directive to support sub includes and added test cases
- [*] My code includes positive and negative tests.
- [*] I have an appropriate description with correct grammar.
- [*] I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), …
> Fix Include Directive

- .github/workflows/regression.yml
They don't work on forks because of lack of secrets. This PR avoids those checks on forks.
> fix: sonar checks on forks.

- .golangci.yml
- .pre-commit-config.yaml
> chore: move all linters to golangci-lint

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- Update README
- Sort out sections to CONTRIBUTING & to a new CHANGELOG
> Updating README & CONTRIBUTING guidelines and adding an initial CHANGELOG

- rule.go
- seclang/rule_parser_test.go
Allow passthrough of variable Negations if not present #264 
> Allow passthrough of variable Negations if not present

- operators/rbl.go
> fix(rbl): close the channel in the sub goroutine

- collection.go
- rule.go
- rule_match.go
- rulegroup.go
- transaction.go
- transaction_test.go
> Improve performance

- seclang/rules_test.go
- testdata/engine/chains.yaml
> remove tests

- http/http_test.go
- seclang/parser_test.go
- testing/auditlog_test.go
> Make sure temp files in tests are removed by using t.TempDir

- README.md
@jptosso You mentioned a separate file, but I figured it's nice and compact enough to add to bottom of README, what do you think?
> Display contributors in README

- http/http_test.go
- internal/io/file.go
- loggers/concurrent_writer.go
- loggers/concurrent_writer_test.go
- operators/operators_test.go
- seclang/directives_log_test.go
- testing/coreruleset_test.go
- transformations/transformations_test.go
> Remove usages of deprecated ioutil

- collection/collection_map.go
- collection/collection_translation_proxy_test.go
- rule.go
- testdata/engine/chains.go
Fix Case sensitive evaluation for v3
> Case sensitive evaluation Fix for v3

- body_buffer_test.go
- loggers/serial_writer_test.go
- seclang/directives_log_test.go
> Remove usage of system /tmp from tests.

- README.md
> Add documentation on mage to README

- seclang/rules_test.go
- transaction.go
- transaction_test.go
by close both request and response buffer even if the former one fails.
Ping @anuraaga 
> chore: improves tx.Clean

- operators/from_file.go
- operators/from_file_test.go
Follows from @anuraaga's comments in https://github.com/corazawaf/coraza/pull/366
> chore: improves from file tests.

- rulegroup.go
This just ports https://github.com/corazawaf/coraza/pull/381 to the `v3/dev` branch.
> v3: Remove unused mutex in RuleGroup

- README.md
Add pre-alpha notice on readme
> add pre-alpha notice

- README.md
> [v3] Display contributors in README

- magefile.go
- operators/detect_sqli.go
- operators/detect_xss.go
- operators/operators_test.go
- operators/pm.go
- operators/pm_from_dataset.go
- operators/pm_from_file.go
- operators/rbl_test.go
This just brings https://github.com/corazawaf/coraza/pull/380 to `v3/dev`.
> chore: organize imports in 3 blocks: stdlib, 3rd party, coraza

- transaction_test.go
Every day you can learn something new about Go ([thanks @anuraaga](https://github.com/corazawaf/libinjection-go/pull/4/files#diff-319bcd394f2d8a0b6fa4f0c851f1b7f5648030e067ff8cb229704e15ed0911a3R102))
> tests: uses testing.TB interface for helper to avoid nil check.

- operators/begins_with.go
- operators/contains.go
- operators/detect_sqli.go
- operators/detect_xss.go
- operators/ends_with.go
- operators/eq.go
- operators/ge.go
- operators/geo_lookup.go
- operators/gt.go
- operators/inspect_file.go
- operators/ip_match.go
- operators/ip_match_from_dataset.go
- operators/ip_match_from_file.go
- operators/le.go
- operators/lt.go
- operators/no_match.go
- operators/pm.go
- operators/pm_from_dataset.go
- operators/pm_from_file.go
- operators/rbl.go
- operators/restpath.go
- operators/rx.go
- operators/streq.go
- operators/unconditional_match.go
- operators/validate_byte_range.go
- operators/validate_nid.go
- operators/validate_nid_test.go
- operators/validate_url_encoding.go
- operators/validate_utf8_encoding.go
This PR does some improvements in the logic of the operators.
> chore: improves logic in the operators.

- seclang/parser_test.go
Follows https://github.com/corazawaf/coraza/pull/433/files#r980406900
Ping @M4tteoP 
> tests: enrich backticks test.

- operators/testdata/validateUtf8Encoding.json
- operators/validate_utf8_encoding.go
It currently returns the opposite
> Fix validateUtf8Encoding

- http/middleware_test.go
- internal/corazawaf/logger.go
- internal/corazawaf/waf.go
- internal/io/nop.go
- loggers/debug.go
Currently logger directives could open files as output over and over. This PR makes sure we close the existing one before setting the new one.
> chore: adds support for closing logs.

- magefile.go
`gofmt` is checked as part of golangci, so the formatting during lint is only really needed for go.mod/sum. It is better to restrict the diff check to those files than use git stash, git stash doesn't work well when files aren't formatted since it will try to restore the stash onto files that have changed during the format and fail to do so. Maybe a way to tweak that, but no need
> Don't git stash when linting

- config.go
This PR accepts more than one rule at time. This reduces the number of clonings.
> feat: changes WAF to accept a slice of rules instead of one rule.

- http/interceptor.go
- internal/corazawaf/transaction.go
- types/transaction.go
> chore: only buffers response body if the mime type is the desired one.

- internal/corazawaf/transaction_test.go
Follows https://github.com/corazawaf/coraza/pull/524#issuecomment-1339848502
> chore: renames transaction tests with engine off 

- .github/workflows/codeql-analysis.yml
Lots of manual tweaks that don't appear to be needed
> Simplify CodeQL workflow

- bodyprocessors/multipart.go
- bodyprocessors/multipart_test.go
- http/middleware.go
- http/middleware_test.go
This PR simplify the multipart test o focus on what matters.
Ping @jptosso @anuraaga
> tests: simplify multipart test.

- internal/corazawaf/waf.go
Some old lines (https://github.com/corazawaf/coraza/commit/46029c0f0862049e5983e4ff55cff38b5b6ab80c#diff-b7d81193324b35778d3c6feb2aa00b46357803142e09e27549afcae2c8b47f0cL24-L26) have been added back with https://github.com/corazawaf/coraza/commit/033db8452e163082e5856827a29b78db4d08c840#diff-b7d81193324b35778d3c6feb2aa00b46357803142e09e27549afcae2c8b47f0cR24. Opening this PR to fix the lint removing the unused code.
> chore: Removes unused code

- testing/engine_test.go
- waf.go
- waf_test.go
Follows from https://github.com/corazawaf/coraza/pull/560/files#diff-081faffa20610c1510154a66fcff0bbf617e176cf3a420ba5f5f1838ceb72503R775
> feat: avoids zero limit on request/response body.

- actions/ctl.go
- actions/expirevar.go
- actions/initcol.go
- actions/setenv.go
- actions/setvar.go
- examples/http-server/main.go
- internal/corazawaf/transaction.go
- internal/seclang/directives.go
- internal/seclang/parser.go
- internal/seclang/rule_parser.go
- macro/macro.go
- operators/validate_nid.go
- testing/engine.go
- transformations/remove_comments.go
Had done a similar pass a while ago focusing on hot spots, but it's good to clean them all up for consistency and readability (no magic `spl` variable)
> Convert split of two items to cut

- internal/seclang/directives.go
This PR adds documentation to the directives in order to first have first class information and second to allow to generate documentation from it. For example https://github.com/corazawaf/coraza.io/pull/167
> docs: adds documentation for directives.

- internal/seclang/directives.go
> docs: improves docs for directives.

- internal/seclang/directives.go
> docs: fixes doc for Include directive.

- internal/corazawaf/transaction.go
- waf.go
- waf_test.go
Following https://github.com/corazawaf/coraza/blob/cc0c32509a39b0354a43fbca528058445fbcd33e/internal/seclang/directives.go#L194
> chore: adds hard limit for body limit.

- magefile.go
Fixed the check of generation as it would only look at the uncommited files and not only look at the generated ones.
> chore: fixes lint check in generation.

- internal/seclang/directives.go
Added some fixes to the directive docs.
> docs: small improvements in the directives docs.

- internal/seclang/directives.go
> docs: adds code backticks for directives.

- internal/corazawaf/rule.go
- magefile.go
Context https://owasp.slack.com/archives/C02BXH135AT/p1675041708025559
This aims to reduce the API surface of data not used.
Ping @liweijian
> Evaluate no return

- types/waf.go
> Needed change: type AuditLogParts []auditLogPart should be exported #628

- actions/allow.go
- http/middleware_test.go
- internal/corazatypes/allow.go
- internal/corazawaf/rulegroup.go
- internal/corazawaf/transaction.go
- internal/corazawaf/waf.go
- testing/engine/allow.go
- types/allow.go
- types/transaction.go
Implements the `allow` disruptive action.
> feat: implement allow disruptive action

- .github/workflows/codeql-analysis.yml
- .github/workflows/regression.yml
- examples/http-server/go.sum
- go.work.sum
Fixes failing CI for [dependabot](https://github.com/apps/dependabot)'s PRs.
> chore: removes CodeQL analysis on the push events

- config.go
Fixes #629 
We can add it back again easily once there is more use case for programattic rules
> Remove WithRules from config

- actions/ctl.go
- actions/ctl_test.go
> tests: adds more coverage for CTL action.

- README.md
There is no specific roadmap right now
> chore(readme): remove roadmap from readme

- internal/seclang/rule_parser.go
Fixes #702 
After checking on the issue, I realized that skipping all whitespace probably is a bug. I think the intent was to skip leading/trailing whitespace only, not middle whitespace.
This reworks the actions parsing code
- Find key/value slices within the string instead of building/allocating them
- Simply use `strings.TrimSpace` around each to ensure only leading/trailing are trimmed and not middle
- Remove quotes after above instead of before so space is still preserved within them
I think the new logic is also clearer, especially handling quotes outside the processing of letters
> Rework actions parsing

- internal/corazawaf/transaction.go
> chore: improves debug log by adding the status.

- auditlog/concurrent_writer.go
- auditlog/formats.go
- auditlog/formats_json.go
- auditlog/init.go
- auditlog/init_tinygo.go
- auditlog/logger.go
- auditlog/logger_test.go
- auditlog/noop_writer.go
- auditlog/serial_writer.go
- config.go
- config_test.go
- internal/corazawaf/waf.go
- internal/seclang/directives.go
Because the word "log" is in the package name
> Reduce stuttering in auditlog package

- bodyprocessors/json.go
- testing/engine/json.go
> Don't remove GET keys in json processor

- internal/corazawaf/rulegroup.go
- testing/engine/skip.go
Decupled from https://github.com/corazawaf/coraza/pull/719/files.
This PR:
- Fixes the skip action containing it within the current phase (Doc: `The skip action works only within the current processing phase`)
- Adds some tests for skip and skipAfter actions
> fix: skip action within the phase, adds tests

- .github/workflows/regression.yml
> fix(ci): remove sonarcloud

- internal/corazawaf/transaction.go
- internal/corazawaf/transaction_test.go
- testing/coreruleset/coreruleset_test.go
> fix(bodyprocessors): fix forcerequestbodyvariable overriding processor

- internal/corazawaf/transaction.go
- internal/corazawaf/transaction_test.go
> fix(bodyprocessors): force response body overrides mime requirements

- magefile.go
Closes https://github.com/corazawaf/coraza/issues/743
> fix: fixes fuzz target.

- .github/workflows/benchmark.yml
- .github/workflows/regression.yml
- .github/workflows/tinygo.yml
- CHANGELOG.md
- README.md
- examples/http-server/README.md
Following https://github.com/corazawaf/coraza/discussions/773
> chore: changes CI to use main branch instead.

- .github/workflows/benchmark.yml
- internal/collections/map.go
- internal/collections/map_test.go
- internal/collections/named.go
- internal/collections/named_test.go
- internal/corazawaf/transaction.go
- internal/corazawaf/transaction_test.go
- internal/corazawaf/waf.go
- internal/corazawaf/waf_test.go
- internal/seclang/directives.go
- internal/seclang/directives_test.go
- internal/seclang/directivesmap.gen.go
- internal/seclang/rule_parser_test.go
> feat: implement SecArgumentsLimit directive

- magefile.go
Borrowed from https://github.com/corazawaf/coraza/pull/822/commits/0189de5fb7caac5326fc9c7d7cef5a0a40f47d35.
Thanks @M4tteoP
> aads more verbosity on go mod tidy errors

- README.md
Small PR that fixes useful links for learning how to use and configure e2e
> fix(readme): E2E Testing links

- .github/workflows/fix-dependabot.yml
Runs mage format on dependabot PRs so they are actually useful.
> chore: runs formatter on dependabot changes.

- .github/workflows/fix-dependabot.yml
Attempts to fix https://github.com/corazawaf/coraza/actions/runs/6429275952/job/17458030044?pr=882#step:6:22
> chore: fixes dependabot updates using ammend to avoid failures when no changes

- .github/workflows/fix-dependabot.yml
Currently we are aiming to ammend the PR with format changes right after it's been opened, however that is inconvenient because a change in this workflow won't trigger the command.
> Fixes dependabot ci

- go.sum
- internal/cookies/cookies.go
- internal/cookies/cookies_test.go
- internal/corazawaf/transaction.go
- internal/corazawaf/transaction_test.go
- internal/url/url.go
> fix: parse multiple cookies with spaces

- experimental/waf.go
- experimental/waf_test.go
- http/middleware.go
- internal/corazarules/rule_match.go
- internal/corazawaf/transaction.go
- internal/corazawaf/waf.go
- internal/corazawaf/waf_test.go
- types/rule_match.go
- waf.go
Follows https://github.com/corazawaf/coraza/issues/919
> feat: adds context to transaction.

- internal/corazawaf/rule.go
- internal/corazawaf/rule_test.go
- internal/corazawaf/waf.go
- internal/seclang/parser.go
This PR improves the way we do logging so we can provide more actionable logs and with better information.
This is based on the observations in the logs of a transaction: https://gist.github.com/jcchavezs/ef0846bf457d2d6ab8b24bfce83860ce
> feat: improves logging.

- internal/seclang/directives.go
Closes https://github.com/corazawaf/coraza/issues/973
Ping @ryanobjc @fzipi
> docs: adds documentation for SecRuleRemoveByTag.

- internal/seclang/rule_parser.go
- internal/seclang/rule_parser_test.go
> fix(seclang): merge chained raw rules

- internal/operators/eq_test.go
> tests: covers zero case in eq operator.

- internal/corazawaf/rule.go
- internal/seclang/rules_test.go
Fixes https://github.com/corazawaf/coraza/issues/1070.
Expansion of Msg and LogData was postponed in a way that `MATCHED_VAR` was only used with the latest matched var after the whole evaluation of the rule, not permitting to log into both error and audit logs more than one match per rule.
This PR tries to address it. The underneath before-and-after shows how the same rule that matched 3 different variables is now logged in both error and audit logs.
Before:
```
[logError][critical] [client "[::1]"] Coraza: Warning. SQL Injection Attack Detected via libinjection [file "default.conf"] [line "33"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: s&nov found within ARGS:arg3: ' AND id3 IS NULL; --"] [severity "critical"] [ver …
```
> fix: logs multiple vars matched by same rule

- renovate.json
> fix: broken renovatebot config

- internal/actions/exec.go
- small fix to allow automated generation of docs from actions
- allow action documentation to be autogenerated
- https://github.com/corazawaf/coraza.io/pull/303
> fix: actions comment

- internal/seclang/directives.go
- internal/seclang/directives_test.go
- internal/seclang/directivesmap.gen.go
- internal/seclang/generator/directivesmap.go.tmpl
- testing/engine/directives_updateactions.go
- adds `SecRuleUpdateActionById` directive
- we need it sometimes
- #929
> feat: add SecRuleUpdateActionById directive

- examples/http-server/go.sum
- internal/seclang/directives.go
- testing/coreruleset/go.sum
Follows https://github.com/corazawaf/coraza/pull/1071
> nits: `SecRuleUpdateActionById` doc

- testing/coreruleset/go.mod
> Revert "fix(deps): update module github.com/coreruleset/go-ftw to v1.1.0 in testing/coreruleset/go.mod"

- testing/coreruleset/go.sum
- testing/engine/variables.go
Follows https://github.com/corazawaf/coraza/pull/1226, address https://github.com/corazawaf/coraza/pull/1226#pullrequestreview-2452007493.
cc @geoolekom
> tests: adds engine tests about args with square brackets

- internal/operators/pm_from_file.go
- testing/engine/operators_with_files.go
Changes:
- Register pmf
- Add test alongside @pmfromfile
fixes #1283
> Add @pmf short alias for @pmFromFile
