corazawaf/coraza

operators/validate_utf8_encoding.go, testdata/operators/validateUtf8Encoding.json
- cleaned up operator
- use native utf8.ValidString func
- fix test results
=> fix(op): move operator to native utf8.ValidString method

transformations/remove_nulls.go
Replaced by golang primitives.
=> fix(removenull): move to golang funcs

.github/FUNDING.yml, .github/workflows/coreruleset.yml, loggers/formats.go, seclang/parser.go, seclang/rule_parser_test.go, seclang/rules_test.go, testdata/engine/variables.yaml, transaction.go, transaction_test.go, waf.go
Now we can use ```coraza.EventLogger``` interface and attach it to ```waf.ErrorLogger``` in order to create web server errors. It will be useful to imitate Nginx and Apache errors like:
```nginx
error_log /some/path/to.log warning
```
=> Add error log support

.github/workflows/go-ftw.yml, go.mod, go.sum, operators/detect_sqli.go, operators/detect_xss.go, operators/operators.go, seclang/directives.go, seclang/directives_test.go
This is an awesome PR, now we do not require libinjection anymore, thank you @bxlxx for your amazing contribution.
Coraza now officially supports detectSQLi and detectXSS without plugins or CGO.
=> feat: integrate libinjection-go

bodyprocessors/multipart.go, bodyprocessors/urlencoded.go, transaction.go, transaction_test.go
#174:
The data structure for ARGS_NAMES and ARGS_GET_NAMES used to be:
```json
{
"": ["name 1", "name 2", "name 3"]
}
```
Now it has become:
```json
{
"name 1": "name 1",
"name 2": "name 2",
"name 3": "name 3",
}
```
There is some redundancy but with the current design it solves the problem for CRS rule 920271 that expects the key name from ARGS_NAMES using MATCHED_VAR_NAME. In the old design MATCHED_VAR_NAME would return just ARGS_NAMES because the arg name was a value, not a key. In coraza v3 there should be a new design for this.
#173:
I've just added the key to MATCHED_VARS:
```go
matchedVars.Add(variableName.String(), match.Value)
```
Tests were added for both cases.
=> fix MATCHED VARS issues

.github/workflows/go-ftw.yml
Fix test go-ftw by updating the organization from jptosso to corazawaf. It applies to both, coraza-caddy and coraza-pcre.
=> fix(test): Update go-ftw action with new org

seclang/rule_parser.go, seclang/rule_parser_test.go
According to #191 report, the secdefault actions for phase 2 are `phase:2,log,auditlog,pass` by default. This PR includes a mechanism to hardcode default actions.
TODO: We must add some logic to avoid repeated default actions, for example, if you use some default actions multiple time you would just concatenate actions:
```
SecDefaultActions "phase:2,log,auditlog,pass"
SecDefaultActions "phase:2,nolog,noauditlog,deny"
```
The previous statement would create the following rule:
```
SecAction "id:1,phase:2"
```
Should we fix that behavior in this PR ?
We should update ```ParseDefaultActions``` and set the following rules:
```
Replacements, action X replaces > action Y:
nolog > log
log > nolog
auditlog > noauditlog
noauditlog > auditlog
A disruptive action replaces all previous disruptive …
```
=> fix: default actions for phase 2 are now hardcoded #191

.pre-commit-config.yaml
I fixed: #213 
git protocol is not supported, so I change the protocol from git:// to https://.
This will be able to work the test wituout remote error.
This is my first OSS contribution!!!
If I am wrong about something, sorry about that and please teach me.
----
=> change the URL protocol(git -> https)

transaction.go, transaction_test.go
ForceRequestBodyVariable was only forcing cases where the content type was empty. Now it will always force.
=> fix(tx): Force Request Body now works

seclang/parser.go, seclang/parser_test.go
The newly implemented Include directive simulates Apache Include. A Coraza user may use it to include files or file patterns from directives, for example.
If you include 1.conf you will get a log message from rules 1, 2, 3, and 4.
```
SecAction "id:1,pass,log"
Include 2.conf
```
```
SecAction "id:2,pass,log"
Include others/*.conf
```
```
SecAction "id:3,pass,log"
```
```
SecAction "id:4,pass,log"
```
Btw, the directive was hardcoded and not created using the plugin interface because of a recursion error:
```
func (*Parser).FromFile(profilePath string) error
FromFile imports directives from a file It will return error if any directive fails to parse or the file does not exist. If the path contains a *, it will be expanded to all files in the directory matching the pattern …
```
=> feat(directive): Implement include directive

types/variables/variables.go
The purpose of using `iota` is to have a unique value for this set of constants without some complicated extra assignment. We can use a simplified `iota` specification to make the whole look more concise.
=> simplified iota definition

.github/workflows/codeql-analysis.yml, .github/workflows/regression.yml, .github/workflows/tinygo.yml, README.md, sonar-project.properties
This PR fixes errors for remote forks, CI will ignore sonarcloud. It also adds the base for the tinygo tests.
- Add support for golang 1.18.x tests
- Add tinygo tag tests
- Fix sonarcloud for remote forks
- Upgrade CodeQL to v2
=> Enhance github actions for sonarcloud and regression

operators/restpath.go, operators/restpath_test.go, transaction.go, types/variables/variables.go, waf.go
Add support for @restpath operator
@respath takes a path pattern as a parameter, it processes the received URL and assigns variables to ARGS_PATH, ARGS_NAMES, and ARGS.
For example:
```
SecRule REQUEST_URI "@restpath /path/{some_id}" "…..chain"
SecRule ARGS_PATH:some_id "!@eq %{user:session_id}" "deny"
```
The previous example will expect some_id to be the same as user:session_id.
This feature is a gamechanger for Coraza API security and it will allow much easier syntax for complex nested endpoints.
=> feat(operator): New RESTPATH operator support

actions/actions.go, actions/redirect.go, testdata/engine/disruptive_actions.yaml
Example:
```
SecRule REQUEST_URI "/redirect" 
"phase:1,id:1,status:302,redirect:https://www.example.com"
```
closes #144
----------------------------------
=> Adding support for the redirect action. closes #144

http/http.go, http/http_test.go, rule.go, seclang/parser.go, seclang/rules_test.go, transaction.go, transaction_test.go, transformations/base64decode.go
This PR follows from #283
Ping @jptosso
=> chore: drops Transaction.ProcessRequest into an own package.

go.mod, go.sum, operators/pm.go, operators/pm_from_file.go, operators/pm_from_file_test.go
This is a huge improvement, memory consumption is 60% less, and execution time was 233% faster
**Old results:**
```
Preparing CRS...
CRS PATH: /var/folders/tf/23czq0cd4wd5v54zcvctvtzw0000gn/T/crs1564927737
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/testing
BenchmarkCRSCompilation-10             3         378610667 ns/op
BenchmarkCRSSimpleGET-10             613           1791376 ns/op
BenchmarkCRSSimplePOST-10            308           3499975 ns/op
PASS
ok      github.com/corazawaf/coraza/v3/testing  13.985s
```
**New results:**
```
Preparing CRS...
CRS PATH: /var/folders/tf/23czq0cd4wd5v54zcvctvtzw0000gn/T/crs1721984072
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/testing
BenchmarkCRSCompilation-10            21          48269002 ns/op …
```
=> replace aho corasick 

seclang/parser.go
I found that the current recursion limit does not work with TinyGo, it probably has a smaller max stack size than Go. I could confirm that 200 is too high and 100 works, didn't check in the middle. 100 seems high enough (even just 1 maybe ?) so I changed the constant, an alternative would be to use build tags to set to 500 normally and 100 only on TinyGo.
**Make sure that you've checked the …
=> Reduce include recursion limit

operators/validate_byte_range.go
`len` and numeric indexing of a string work on bytes so no need to convert
=> Don't copy to bytes when validating byte range

.pre-commit.hook, magefile.go
This adds a command for installing a precommit hook. The current precommit infrastructure has a couple of issues
- Requires installing external tool, `precommit` (and python if not installed yet)
- Requires installing the actual linting tools as [here](https://github.com/corazawaf/coraza/blob/v2/master/.github/workflows/lint.yml#L16). More problematically, requires reinstalling if updated.
These aren't the end of the world, but we can continue to support all our tooling while only requiring Go. This adds the command `go run mage.go precommit` which copies a pre-commit hook to `.git` which simply runs `go run mage.go check`. `go run mage.go check` will run the same across CI, dev machines, etc even if we update tool versions, no version maintenance required by users.
If this is accepted, …
=> Add command for installing precommit hook

go.mod, go.sum, testing/modsecurity_test.go
I don't think there's much more to try to reduce overhead other than reducing overhead when reading log statements that aren't actually outputed for the current log level (some string conversions in the cgo bridge, for a string that's eventually dropped). But I think if we have similar performance to this, then we're in a good place
https://github.com/anuraaga/go-modsecurity/commit/b9a4099778df0cbf27d2a690a09240fe8f4f2593
The effect will be biggest with large bodies, previously there was this buffer copy
https://github.com/anuraaga/go-modsecurity/commit/b9a4099778df0cbf27d2a690a09240fe8f4f2593#diff-63ab601287b8b9c040760fe0bdd288f55b73f37cd7e4f1e519bea2bd43a18bbaL246
I'm a bit scared to make the change since not sure why anyone would append newline if not required, but I can't think of the …
=> Reduce some data copies in modsecurity bridge

magefile.go
Allows running lint on uncommitted files (formatting check uses git diff after formatting)
=> Run lint before formatting

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/regression.yml, .github/workflows/tinygo.yml, .golangci.yml, CONTRIBUTING.md
=> [v3] Use mage commands in CI instead of pre-commit

SECURITY.md, go.mod, operators/pm_from_dataset.go, operators/pm_from_dataset_test.go, rule.go, seclang/directives.go, seclang/directives_test.go, seclang/parser.go, sonar-project.properties
WASM support is an essential feature of Coraza v3, but users cannot fully enjoy its potential because of file reading limitations. For this reason, `SecDataset` is a decent replacement for .data files. It's also easier to watch files for reloading on .conf files.
**Compatible operators are:**
- **ipMatchFromDataset:** TBI
- **pmFromDataset:** Implemented
Messing with the seclang (apache directives) syntax will break regression for modsecurity compatible engines.
**Description:** Emulates .data files by inserting multiple strings, line by line. Operators such as @pmFromDataset can use these datasets as the source of dictionary matching.
**Syntax:** SecDataset DATASET_NAME \`...\`
**Sample:**
```apache
SecDataset sample_dataset `
word1
word2
word3
`
SecRule REQUEST_URI "@pmFromDataset …
```
=> add dataset support

operators/ip_match_from_dataset.go, operators/ip_match_from_dataset_test.go, operators/ip_match_from_file.go, operators/operators.go, operators/pm_from_dataset.go, operators/pm_from_file.go
Follows https://github.com/corazawaf/coraza/pull/361 (Thank you so much @jptosso!).
- Parses the input file in `ipMatchFromFile`
Based on the `pmFromFile` implementation, the PR proposes to also ignore empty and comment lines (#...) in the `ipMatchFromFile` operator.
- Implements the `ipMatchFromDataset` operator. 
`ipMatchFromDataset` is the second operator that can benefit from the introduction of `SecDataset`. This PR proposes an implementation of it.
- chore: removes misleading comments about snort syntax in `pmFromDataset` and `pmFromDataset`. See [comment](https://github.com/corazawaf/coraza/pull/361#discussion_r956138113).
**Question**: Do I have to register the new operator? I'm aware of a list of operators inside [operators.go](https://github.com/corazawaf/coraza/blob/v3/dev/opera …
=> Implements ipMatchFromDataset, parsing for ipMatchFromFile

operators/from_file.go, operators/from_file_test.go, operators/ip_match_from_file.go, operators/ip_match_from_file_test.go, operators/ip_match_test.go, operators/operators_test.go, operators/pm_from_file.go, seclang/parser.go, seclang/rule_parser.go
Currently files are loaded on parsing and passed down to operators (e.g. pmFromFile) inside the options, this is inconvenient because we have custom logic for them (making useless the interface) but also making it hard to implement things like lazy load of the data.
Ping @anuraaga 
=> chore: loads file inside operator when using FromFile.

actions/append.go, actions/ctl.go, actions/setenv.go, actions/severity_test.go, bodyprocessors/xml_test.go, operators/operators_test.go, seclang/directives.go, seclang/rule_parser_test.go, waf.go
As reflection (using %v interpolator) isn't fully supported, hence we stick to string (%s) when possible.
**Note:** not every usage of `%v` has been replaced as some require other treatment to become string (e.g. `[]error` or `[]string`)
Ping @anuraaga 
=> chore: improves errors on tinygo.

examples/http-server/main.go, seclang/body_test.go, seclang/directives_log_test.go, seclang/directives_test.go, seclang/parser.go, seclang/parser_test.go, seclang/rule_parser_test.go, seclang/rules_http_test.go, seclang/rules_test.go, testing/auditlog_test.go, testing/coraza_test.go, testing/coreruleset_test.go
I don't think it's common to have an err result just for a nil check, but it makes the `NewParser` method quite a bit harder to use. All the logic that can generate errors is in parsing methods, this just creates a default struct.
Note that if going with #371, this would be superceded as we would want to keep all configuration in the same place at the entrypoint to the library, and this type would probably go away.
=> Remove err return from NewParser

actions/append.go, actions/ctl.go, actions/setenv.go, actions/setvar.go, actions/skipafter.go, magefile.go, operators/detect_sqli.go, operators/detect_xss.go, operators/pm.go, operators/pm_from_file.go, operators/rbl_test.go, rule.go, rulegroup.go, seclang/directives.go, seclang/parser.go, testing/profile.go, transaction.go, transformations/base64decode_test.go, transformations/url_encode_test.go, waf.go
Update the `format` build target to organize imports in 3 blocks: stdlib, 3rd party dependencies, and current project dependencies. This is a common practice and makes it easier to see, for any given file, what external dependencies are being used there.
=> chore: organize imports in 3 blocks: stdlib, 3rd party, coraza

internal/strings/strings.go, loggers/formats.go, seclang/directives_log_test.go, testing/coreruleset_test.go, waf.go
Currently, random string generation uses cryptographic random which is very slow. Random strings are used for identifiers and don't seem to have any cryptographic significance (please confirm!) so this removes that, and also applies some smaller optimizations.
It stood out in profiles within non-alloc, unfortunately the numbers are still quite dominated by allocator / GC so reducing garbage will be an ongoing effort.
After
```
Preparing CRS...
CRS PATH: /var/folders/vx/38td0k79201f9zn_myzbqx_40000gn/T/crs1403234494
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/testing
BenchmarkCRSSimplePOST
BenchmarkCRSSimplePOST-10    	     541	   2162702 ns/op
PASS
```
Before
```
Preparing CRS...
CRS PATH: /var/folders/vx/38td0k79201f9zn_myzbqx_40000gn/T/crs2813219423
goos: darwin …
```
=> Optimize random string generation

internal/strings/strings.go
I went with adding a doc instead of renaming but if others feel strongly could rename. In my experience, which may include too old languages ;), pseudorandom tends to be the default, so e.g. the standard library provides a random and a secure random or crypto random - so I've never assumed the word random to assume cryptographically secure, and have had the opposite reaction of often finding it to be using cryptographically secure when just called random. This may just be me though :) But especially for an internal function, the shorter name is another pro I guess.
=> Document that RandomString is pseudorandom

magefile.go
Currently, lint was running golang-ci lint a then running the format command to later inspect the diff. If a user had unstagged files, lint would fail anyways because git diff would list those unstaged files which is akward because the diff was already there and wasn't originated by the format command instead. In this change we stash unstagged changes, run diff and then unstash them.
=> fix: improves mage lint user experience.

testing/coreruleset_test.go
Mainly removed the usage of `defer` in a loop.
=> chore: avoids too many open files error when running CRS.

operators/pm.go, operators/pm_from_dataset.go, operators/pm_from_file.go
@jcchavezs Mostly to validate against https://github.com/petar-dambovaliev/aho-corasick/pull/9/files. Since this doesn't allocate the result array, I guess even if `FindN` was provided we would stick to this pattern. If `FindAllFunc` were added we would use it though
=> Use iter for pm operator instead of always finding all when capturing

internal/strings/strings.go, internal/strings/strings_test.go
Always forget that rand objects aren't threadsafe
Fixes #429
=> Make RandomString concurrent-safe

seclang/parser.go, seclang/parser_test.go
Closes https://github.com/corazawaf/coraza/issues/432.
This PR basically evolves the conversation that we had here: https://github.com/corazawaf/coraza/pull/412#discussion_r966533852.
The `inQuotes` (now `inBackticks`) logic comes before considering lines that are comments. Therefore a trailing backtick in a comment is considered a valid backtick.
- One solution I see is the one implemented in the PR, explicitly ignoring a line that starts with `#` when looking for backticks. 
- An alternative to don't complicate an already quite tricky line would be just adding the logic that skips comment:
```
if line[0] == '#' {
continue
}
if !inBackticks && line[lineLen-1] == '`' {
inBackticks = true
...
```
before the backticks logic. This implies that all the lines starting with `#` will be ignored, …
=> Fix parser backticks 

actions/msg.go, internal/strings/strings.go, internal/strings/strings_test.go, seclang/rule_parser.go, seclang/rules_test.go, testing/engine/variables.go
SecLang rules generally use expressions where it is expected that escape sequences are preserved in the regex itself. This doesn't work for unicode sequences though, so we unquote only unicode sequences.
=> Remove unescaping in string handling and use proper unicode regex syntax.

collection/collection_map.go, collection/collection_proxy.go, collection/collection_translation_proxy.go, internal/corazawaf/rule.go, internal/corazawaf/rulegroup.go, internal/corazawaf/transaction.go, internal/seclang/directives.go, internal/seclang/rule_parser.go, internal/seclang/rules_test.go, loggers/formats_json.go, operators/operators_test.go, operators/pm_from_file.go, operators/rbl.go, transformations/cmd_line.go, transformations/compress_whitespace.go, transformations/remove_comments_char.go, transformations/transformations_test.go
It's conventional to use `nil` for empty slice and maybe a tiny bit faster.
Applied this automatically with GoLand
=> Don't explicitly initialize empty slices

internal/corazawaf/transaction_test.go, macro/macro.go
No need to do any allocation for a single token macro
After
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/corazawaf
BenchmarkMacro
BenchmarkMacro/%{tx.a}
BenchmarkMacro/%{tx.a}-10         	32559846	        37.08 ns/op
BenchmarkMacro/%{tx.a}_%{tx.b}
BenchmarkMacro/%{tx.a}_%{tx.b}-10 	 9336523	       128.8 ns/op
BenchmarkMacro/goodbye_world
BenchmarkMacro/goodbye_world-10   	292027911	         4.070 ns/op
PASS
```
Before
```
BenchmarkMacro
BenchmarkMacro/%{tx.a}
BenchmarkMacro/%{tx.a}-10         	19797242	        55.83 ns/op
BenchmarkMacro/%{tx.a}_%{tx.b}
BenchmarkMacro/%{tx.a}_%{tx.b}-10 	 9750448	       120.0 ns/op
BenchmarkMacro/goodbye_world
BenchmarkMacro/goodbye_world-10   	55078822	        21.45 ns/op
PASS
```
=> Add fast path for macro with single token

examples/http-server/main.go, internal/corazawaf/logger.go, internal/corazawaf/waf.go, internal/corazawaf/waf_test.go
This PR adds support for stdout as output for debug log. Most of the references to stdout in modsec world points to `/dev/stdout` as the target although it isn't idiomatic to Windows.
=> feat: adds support for stdout.

internal/corazawaf/waf.go, internal/corazawaf/waf_test.go, waf.go
`waf.NewTransactionWithID(ctx, id)` can be used by connectors to use the web server ID instead of coraza generated IDs. Useful for logging.
=> add waf.NewTransactionWithID

http/http.go, http/interceptor.go, http/middleware.go, http/middleware_test.go
Not sure when, but Go has the correct protocol version now. This removes the hack workaround and backfills tests
=> Reads the request protocol instead of hacks

README.md, actions/ctl_test.go, http/http_test.go, http/middleware.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go, internal/corazawaf/waf_test.go, internal/seclang/body_test.go, internal/seclang/parser_test.go, internal/seclang/rules_test.go, operators/operators_test.go, operators/pm_from_dataset_test.go, operators/rbl_test.go, operators/restpath_test.go, operators/rx_test.go, operators/validate_byte_range_test.go, testing/auditlog_test.go, testing/coreruleset/coreruleset_test.go, testing/engine.go, waf.go
Context isn't used and won't be used in the short term. Although there are many use cases (e.g. deadlines for expensive analysis) the impact in the proxy-wasm env makes it not viable for V3 as goroutines can be spawn freely like in regular Go.
=> chore: drops context first param.

internal/corazawaf/body_buffer.go, internal/corazawaf/body_buffer_tinygo_test.go, testing/coreruleset/coreruleset_test.go
Currently in tinygo envs, if the writing data was bigger than max limit of body, the entire body was still written. This PR truncates the body as in tinygo (as opposed to Go) we keep the entire body in memory. 
=> chore: makes sure body payload has a limit in tinygo.

internal/corazawaf/waf.go, internal/sync/pool.go, internal/sync/pool_std.go, internal/sync/pool_tinygo.go, internal/sync/pool_tinygo_test.go
TinyGo doesn't seem to implement any sort of pooling
https://github.com/tinygo-org/tinygo/blob/release/src/sync/pool.go#L18
I will probably propose using this simple implementation there too, but in the meantime it's fairly simple for us to have two implementations and could be worth it
=> Implement a simple sync.Pool for TinyGo

coraza.conf-recommended
This PR proposes to port [modsecurity.conf-recommended fix](https://github.com/SpiderLabs/ModSecurity/commit/622eb9e6c860ade1e2195d316dfbd86ce5710445) to coraza.conf-recommended.
This fix follows a vulnerability discovered by Terjanq documented [here](https://terjanq.medium.com/waf-bypasses-via-0days-d4ef1f212ec#:~:text=a%20backend%20server.-,XML%20request%20body%20processor,-The%20regular%20expression): regexes for parser activation rules may interpret the content-type differently than the server. It can lead to a complete WAF bypass.
=> Fix: Adjust parser activation rules in coraza.conf-recommended

.github/workflows/close-issues.yml
It is somehow annoying that we are closing issues for ideas we want to cover in future versions. Should we only close issues with some smarter criteria? For example, issues where we wait some response for a bug, or similar?
=> chore: do not close future versions work

bodyprocessors/bodyprocessors.go, bodyprocessors/json.go, bodyprocessors/multipart.go, bodyprocessors/multipart_test.go, bodyprocessors/urlencoded.go, bodyprocessors/urlencoded_test.go, bodyprocessors/xml.go, bodyprocessors/xml_tinygo.go, internal/corazawaf/transaction.go, internal/corazawaf/waf.go
Function calls accepting collections as a parameter are copying the entire array each invocation. We had a similar issue in libinjection-go where the array was many many thousands of elements and a huge problem, but 92 is still too big for always being copied on function call. This switches to a slice which is more idiomatic in Go, though in a follow up will look at changing to a struct pointer which should be faster than a slice for fixed content like this. Because collections are pooled since #464 there isn't extra allocation overhead for switching from array to slice
=> Use slice for collections instead of array

testing/coreruleset/coreruleset_test.go, testing/coreruleset/go.mod, testing/coreruleset/go.sum
I think it's good to avoid writing to tmp when not needed, especially when not cleaning it up. While it would be possible to restructure the tests to clean up, since CRS is small it seems fine to just keep it in memory
=> Keep CRS in memory instead of writing to tmp in tests

magefile.go
Newly introduced tests about the example HTTP server and CRS are only executed by running `mage test`, not `mage coverage`. It leads to not actually running these tests inside the CI (example of green CI with a broken commit test [here](https://github.com/corazawaf/coraza/actions/runs/3384997844/jobs/5622631559)).
This PR proposes to add them also in the `coverage` command.
For `/testing/coreruleset` I had to remove the `-race` flag because it was leading to fail the test with the following error:
```
{"level":"fatal","caller":"/Users/user/go/pkg/mod/github.com/coreruleset/go-ftw@v0.4.0/runner/run.go:144","error":"read tcp 127.0.0.1:65384->127.0.0.1:59909: i/o timeout","time":"2022-11-03T12:48:58+01:00","message":"failed sending request to destination &{DestAddr:127.0.0.1 Port:59909 …
```
=> Fix: adds http-server and coreruleset tests to coverage command, enabling them in CI

.github/workflows/regression.yml, http/middleware.go
CRS-related unit tests have been just added to the CI yesterday with https://github.com/corazawaf/coraza/pull/492.
Therefore, the PR  https://github.com/corazawaf/coraza/pull/483 just merged today related to CRS response body tests has not been checked by the CI, but only locally (where I'm currently running Go 1.19).
Inside the middleware, in order to make the request body readable again, we rely on `req.Body = io.NopCloser(reader)`.
In Go 1.18, unlike Go 1.19, `io.NopCloser` does not also implement `WriterTo` whenever its input does ([Ref](https://tip.golang.org/doc/go1.19#minor_library_changes)). This method is internally called by the Handler inside the test to echo the request body into the response body triggering CRS response body tests.
This PR proposes to backport the new logic …
=> Fix CRS Regression tests - Go 1.18

internal/corazawaf/transaction.go, types/transaction.go
Related to https://github.com/corazawaf/coraza/issues/497 and its port (https://github.com/corazawaf/coraza-proxy-wasm/issues/68).
This PR proposes to add `RequestBodyAccessible()` and `ResponseBodyAccessible()` returning, just like the name explicit, `RequestBodyAccess` and `ResponseBodyAccess` booleans. 
I think that would be nice to be aware of `RequestBodyAccess` and `ResponseBodyAccess` statuses from the connectors. It would permit optimizing bodies' actions such as avoiding buffering the bodies if they are not going to be analyzed.
=> Export Request/Response BodyAccess values

config.go, config_test.go
clone is supposed to return an immutable copy of the config but forgot to deep copy its slice
=> Copy rules slice when cloning config

http/interceptor.go, http/interceptor_test.go, http/middleware.go, http/middleware_test.go
This PR attemps to prove the usefulnes of https://github.com/corazawaf/coraza/pull/499 by refactoring the logic and avoiding buffering request/response body when no need.
Ping @M4tteoP @anuraaga @jptosso 
=> feat: optimize body buffering.

http/interceptor.go, http/middleware.go, http/middleware_test.go, internal/corazawaf/transaction.go, types/transaction.go
Follows https://github.com/corazawaf/coraza/pull/499, Just like `RequestBodyAccess` and `ResponseBodyAccess`, connectors could benefit from retrieving the current status of the engine. I also added a note to explicitly tell that it is the **current** status per-transaction basis in order to be aware of using it without making wrong assumptions.
=> Exports IsRuleEngineOff

http/interceptor.go, http/middleware.go, internal/corazawaf/transaction.go, internal/seclang/rules_test.go, types/transaction.go
While these are breaking changes, I think the naming describes better what they do.
=> breaking: rename methods for a better description of what they do.

internal/strings/strings.go, transformations/url_decode.go, transformations/url_decode_uni.go, transformations/url_decode_uni_test.go
Transformation cache will help a lot but anyways we shouldn't allocate where there's no need to
Also wraps the result buffer instead of copying
After
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/transformations
BenchmarkURLDecode
BenchmarkURLDecode/normal/
BenchmarkURLDecode/normal/-10         	563965651	         2.112 ns/op
BenchmarkURLDecode/normal/helloworld
BenchmarkURLDecode/normal/helloworld-10         	212564259	         5.637 ns/op
BenchmarkURLDecode/normal/hello+world
BenchmarkURLDecode/normal/hello+world-10        	46705327	        25.33 ns/op
BenchmarkURLDecode/normal/%E3%83%8F%E3%83%AD%E3%83%BC%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89
BenchmarkURLDecode/normal/%E3%83%8F%E3%83%AD%E3%83%BC%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89-10         	14283956	        84.26 …
```
=> Passthrough string in url decode transformations when no decoding

config_test.go, transformations/length.go, transformations/length_test.go
Doc says # of bytes
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#length
As does ModSec implementation
https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/transformations/length.cc#L41
=> Return number bytes, not runes, in length transformation

internal/strings/strings.go, transformations/compress_whitespace.go, transformations/compress_whitespace_test.go
After
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/transformations
BenchmarkCompressWhitespace
BenchmarkCompressWhitespace/#00
BenchmarkCompressWhitespace/#00-10         	571122726	         2.125 ns/op
BenchmarkCompressWhitespace/test
BenchmarkCompressWhitespace/test-10        	248496358	         4.828 ns/op
BenchmarkCompressWhitespace/test_case
BenchmarkCompressWhitespace/test_case-10   	29280343	        40.49 ns/op
BenchmarkCompressWhitespace/test____case
BenchmarkCompressWhitespace/test____case-10         	25941014	        46.05 ns/op
BenchmarkCompressWhitespace/_test__c__as___
BenchmarkCompressWhitespace/_test__c__as___-10      	17068617	        70.48 ns/op
PASS
```
Before
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/transformations …
```
=> Passthrough non-transformed strings in compressWhitespace

config_test.go, internal/strings/strings.go, transformations/css_decode.go, transformations/css_decode_test.go
After
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/transformations
BenchmarkCSSDecode
BenchmarkCSSDecode/#00
BenchmarkCSSDecode/#00-10         	463445419	         2.597 ns/op
BenchmarkCSSDecode/hello_world
BenchmarkCSSDecode/hello_world-10 	319812020	         3.715 ns/op
BenchmarkCSSDecode/test\a\b\f\n\r\t\v\?\'\"\\x00\12\123\1234\12345\123456\ff01\ff5e\_\\x00__string
BenchmarkCSSDecode/test\a\b\f\n\r\t\v\?\'\"\\x00\12\123\1234\12345\123456\ff01\ff5e\_\\x00__string-10         	 9009106	       133.5 ns/op
PASS
```
Before
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/transformations
BenchmarkCSSDecode
BenchmarkCSSDecode/#00
BenchmarkCSSDecode/#00-10         	264846192	         4.522 ns/op
BenchmarkCSSDecode/hello_world …
```
=> Passthrough non-transformed strings (to some degree) in cssDecode

config_test.go, internal/strings/strings.go, transformations/md5.go, transformations/md5_test.go, transformations/sha1.go, transformations/sha1_test.go
After
```
BenchmarkSHA1
BenchmarkSHA1/#00
BenchmarkSHA1/#00-10         	555318814	         2.120 ns/op
BenchmarkSHA1/1234567890
BenchmarkSHA1/1234567890-10  	11032917	       108.5 ns/op
BenchmarkMD5
BenchmarkMD5/#00
BenchmarkMD5/#00-10         	563206208	         2.136 ns/op
BenchmarkMD5/1234567890
BenchmarkMD5/1234567890-10  	 7238055	       165.6 ns/op
```
Before
```
BenchmarkSHA1
BenchmarkSHA1/#00
BenchmarkSHA1/#00-10         	10593223	       110.5 ns/op
BenchmarkSHA1/1234567890
BenchmarkSHA1/1234567890-10  	10065594	       123.5 ns/op
BenchmarkMD5
BenchmarkMD5/#00
BenchmarkMD5/#00-10         	 7257741	       164.5 ns/op
BenchmarkMD5/1234567890
BenchmarkMD5/1234567890-10  	 6698254	       175.3 ns/op
```
=> WrapUnsafe in hash transformations

internal/corazawaf/rule.go, internal/corazawaf/rulegroup.go
It does happen to work and enables TinyGo to work well
See https://github.com/tinygo-org/tinygo/issues/3354 for context
I found that TinyGo does not handle map keys with embedded variable-length fields (basically just `string` I guess) well, converting to interface and using reflection, which causes allocations and general slowness.
The arg key string coincidentally has a stable pointer for our purposes here...so we can use it.
This is an alternative to #552 but is very hacky. If it seems like too much, we can give up on the cache for now. But I do think the cache is important for performance so maybe we can live with it. I would be surprised if FTW were to pass in the future if a bug was caused by the pointer stability property not being valid anymore, so that safety measure is there, I …
=> Use pointer for arg key in cache key

internal/corazawaf/rule.go, internal/corazawaf/transaction.go, internal/corazawaf/waf.go
Previously I thought TinyGo problems were solved by #553 but I hadn't let the bench run long enough to see it get slower over time, an indication of memory leak.
It seems like there is a bug in TinyGo - https://github.com/tinygo-org/tinygo/issues/3358
The issue only happens with largeish values it looks like - so using a pointer for the value appears to make the problem go away. This is not ideal as it means heap allocation, something we wanted to avoid with this cache. But performance does seem to be a bit better on FTW (and presumably more so with larger payloads) with this change compared to without a transformation cache, so we can live with it until debugging further. The heap allocated object is a fixed, smallish size (it contains a couple of slices, not data itself) so it's not …
=> Allocate transformation cache value on heap

actions/ctl.go, actions/ctl_test.go
Follows https://github.com/corazawaf/coraza/pull/526:
- simplifies `parseCtl` with `strings.Cut`.
- adds a `parseCtl` specific test.
- removes a redundant test.
=> fix: minor cleanup in parseCtl, adds parseCtl test 

internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go
This is particularly an important change as different instances of WAF would reuse the same pool of transactions which would end up on reusing the body buffer settings of the first one declared.
Ping @anuraaga
=> chore: makes txPool a WAF attribute to avoid globals.

http/middleware.go, http/middleware_test.go, internal/corazawaf/body_buffer.go, testing/coreruleset/coreruleset_test.go
Currently, the buffer file is seeked as soon as `Reader` is called, but is particularly problematic as even in our middleware code, it's natural to call `Reader`, then `ProcessRequestBody`, then actually read from the reader when there is no interruption. Currently, the reader will not return the body for a disk buffer as it would have already been consumed by `ProcessRequestBody`, the seek won't be at 0 anymore - I guess in general we don't have much test coverage that triggers disk buffer writes, FTW would catch it if the payloads were big enough for that and assuming the response body is verified.
Instead, we should keep a separate iterator independent from the file write position. We can follow up with optimizations to implement more interfaces like `Len()` but want to keep the bug …
=> Don't seek output file when reading from buffer

CHANGELOG.md, config.go, examples/http-server/main.go, http/middleware_test.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go, internal/seclang/rules_test.go, testing/coreruleset/coreruleset_test.go, waf.go
I went for removing the type as it was meaningless IMO.
Closes #555
=> chore: dropping internal logger type used in the public API.

.github/workflows/fuzz.yml, magefile.go, transformations/base64decode_test.go, transformations/cmd_line_test.go
Being a security product, it seems like it will be good to run some fuzz tests especially on our string crunching code. This adds a couple of fuzz tests to start and a nightly run.
=> Add infrastructure for and a couple of fuzz tests

internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go
Currently if there is an interruption in a previous phase and one call a ulterior phase, it will do the entire analysis, possible not returning the former interruption. While this is a programatic error, given the nature of the library we should let the user know this is happening.
=> chore: implements idempotency for phase calling.

internal/corazawaf/transaction.go
Follows https://github.com/corazawaf/coraza/pull/571 working on idempotency: avoids calling twice any of the `ProcessX` functions. I think it is more about making explicit an implicit requirement that was addressed by the connectors' logic, rather than a design change. What do you think?
=> chore: idempotency on ProcessX functions

examples/http-server/go.mod, examples/http-server/go.sum, go.mod, go.sum, go.work.sum, magefile.go, operators/detect_sqli.go, operators/detect_sqli_test.go, operators/detect_xss_test.go, testing/coreruleset/go.mod, testing/coreruleset/go.sum
These do a lot of string crunching and are good targets for fuzz. Notably, it found a couple of crashes in XSS detection https://github.com/corazawaf/libinjection-go/pull/15
=> Add fuzz tests for injection operators

http/middleware.go, http/middleware_test.go, internal/corazawaf/body_buffer.go, internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go, internal/corazawaf/waf_test.go, internal/seclang/body_test.go, internal/seclang/rules_test.go, testing/coreruleset/coreruleset_test.go, testing/engine.go, testing/modsecurity_test.go, types/transaction.go
Currently we were blindly copying the request body from the upstream call to the
RequestBodyWriter and then back to the downstream handler in many cases wasting resources
because body was beyong what coraza should analyse and or request end up being rejected
due to the size. This method allows to early check conditions around the body size to be
able to resolve a rejecting before copying the the body (or part of it).
The design is similar to https://github.com/SpiderLabs/ModSecurity/blob/8c409149c9e03c36d3feb767f74a07405bc1a685/src/transaction.cc#L1038 as suggested by @M4tteoP 
Missing:
- tests multiwrite
- calling ProcessRequestBody if the limit is hit
=> Append request body

.github/workflows/regression.yml, README.md, internal/corazawaf/rule.go, internal/corazawaf/rule_option_default.go, internal/corazawaf/rule_option_multiphase.go, internal/corazawaf/rulegroup.go, magefile.go, types/phase.go
For coraza-proxy-wasm, we have been discussing evaluation escape because Envoy will send request headers upstream before waiting for request body. As we execute phase 1 when headers are available, phase 2 rules will not have been run by then. Unfortunately, many rules in CRS are set to phase 2 but match against both phase 1 and phase 2 variables, for example the log4shell rule. Malicious headers can be sent upstream without checking them.
As we do have a good idea of when variables are ready for many of them, it is possible for us to infer which phases the rule should run. Connectors should generally know when their server/proxy will send headers before body or not, so this opts in as a build tag for now. It could be a runtime flag in the future if we find a use case for it, e.g. a server …
=> Support evaluation of rules in multiple phases

internal/seclang/parser.go, internal/seclang/parser_test.go, internal/seclang/testdata/glob/rules1.conf, internal/seclang/testdata/glob/rules2.conf
Currently parser mutates its state in order to resolve relative imports, however when an import file, it keeps the reference of the current directory relatively to the failing file, leading to an error in the next file (because the currentDir reference is stuck in the previous one).
At some point we need to change this, however it will require some changes in the parser and directives.
=> fix: fixes side effects between calls when a file does not exist in parser

operators/pm.go
Referencing https://github.com/corazawaf/coraza/pull/585
Our newest implementation of aho-corasick is faster than re2
=> remove old TODO

actions/append.go, actions/prepend.go, examples/http-server/main_test.go, http/interceptor.go, internal/corazawaf/body_buffer.go, internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go, internal/seclang/rules_test.go, rules/transaction.go, testing/engine.go, types/transaction.go, types/waf.go
Follows https://github.com/corazawaf/coraza/pull/560, implemented corresponding functions for the response body. 
actions related to ContentInjection require extra care. See: https://github.com/corazawaf/coraza/pull/589
=> implements ReadResponseBodyFrom and WriteResponseBody

macro/macro.go
Should be a bit faster, I think it's clearer too
=> Use unknown instead of nil for macro without variable

examples/http-server/main_test.go, http/interceptor.go, http/middleware_test.go
This PR fixes
```
2023/01/30 22:44:14 http: superfluous response.WriteHeader call from github.com/corazawaf/coraza/v3/http.wrap.func1 (interceptor.go:126)
```
=> fix: fixes the superflous header write.

coraza.conf-recommended, examples/http-server/testdata/request-body-limits-processpartial.conf, examples/http-server/testdata/response-body-limits-reject.conf, examples/http-server/testdata/response-body.conf, examples/http-server/testdata/response-headers.conf, http/middleware_test.go, internal/seclang/directives.go, internal/seclang/directives_log_test.go, testing/engine/ctl.go, testing/engine/match.go
Follows https://github.com/corazawaf/coraza/pull/519:
- updates `SecDebugLogLevel` doc
- updates a few `SecDebugLogLevel` values across tests
- fixes conf-recommended file
=> chore: updates directives doc about SecDebugLogLevel

.github/workflows/tinygo.yml, bodyprocessors/json.go, collection/collection.go, internal/collections/map.go, internal/collections/map_test.go, internal/collections/named.go, internal/collections/named_test.go, internal/collections/single.go, internal/collections/single_test.go, internal/collections/sized.go, internal/collections/sized_test.go, internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, testing/engine_test.go
Currently there is a confusing `Data()` method on `Map` which looks very similar to `FindAll`. It's a bit more optimized for string formatting, but not by much.
This moves the string formatting to the collections themselves - it seems easier to reason about, more flexible, and more performant. Some other uses of Data are removed or made internal.
=> Move debug formatting to collections and remove Map.Data

config.go, http/middleware_test.go, internal/corazawaf/transaction_test.go, internal/corazawaf/waf.go, internal/corazawaf/waf_test.go, internal/seclang/directives.go, internal/seclang/directives_test.go, waf.go, waf_test.go
Currently in memory limit default value is hardcoded to 1GB which is inconvenient when we set low values for body limit e.g. in tests as we also need to set the in memory limit despite the fact it is part of the test or not.
=> Backfills in memory limit

internal/seclang/directives.go, internal/seclang/directives_test.go, internal/seclang/parser.go, internal/seclang/parser_test.go, internal/seclang/rule_parser_test.go, types/waf.go
Currently if the directive is invalid (e.g. a valid directive without options) the parser would not fail. This PR changes that so that the directives will fail if malformed.
**Important:** Until now we are operating under the assumption **the only direction** which does not require options is `directiveSecResponseBodyMimeTypesClear` (to be confirmed by @airween @dune73 @fzipi)
Funny note: this has been found by trying to resurrect the playground
=> fix: fixes the parser to avoid invalid rules.

coraza.conf-recommended, internal/seclang/directives.go, internal/seclang/directives_test.go, internal/seclang/directivesmap.gen.go, internal/seclang/generator/directivesmap.go.tmpl
We drop support for this, aligning with modsec 3 as described in https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#sectmpdir
=> chore: removes support for SecTmpDir.

actions/nolog.go
Initialization of actions happen once in the WASM and mutate the rules, however evaluation are executed per transaction and mutating the rule shouldn't happen as it leads to race conditions and unexpected behaviours. See https://github.com/corazawaf/coraza-caddy/issues/44.
=> chore: avoids mutating the rule during evaluation.

README.md
Update readme to show codecov instead of sonarcloud
=> chore: change readme coverage

internal/corazarules/rule_match.go, internal/corazawaf/rule.go, types/rule_match.go
We only have one spot that checks for this and can just inline the check. If for some reason a user runs into it they would be able to do similar, there isn't any pointer involved so we don't lose safety vs nil dereference by removing the function.
I tried to remove use of empty match completely without completely rewriting but ran into issues with chains. I think the handling really just needs to be significantly rewritten for SecMark / SecAction, filed #676 for it.
In the meantime, we should remove from the public API.
Fixes #636
=> Remove MatchData.IsNil

internal/seclang/rule_parser.go
Use string builder in parseActions() function to efficiently concatenate strings and optimize memory usage. go bench profile (testing/coreruleset) shows less allocations in seclang.parseActions function.
=> Use string builder in parseActions() to optimize memory usage.

internal/corazawaf/rule.go, internal/corazawaf/transaction_test.go, internal/seclang/directives.go, internal/seclang/rule_parser.go
I am investigating at-rest memory usage of coraza-proxy-wasm and digging through parsing / setup code as part of it. Nothing in this PR is particularly impactful yet but will send some cleanup PRs / microoptimizations as I find any.
=> Small cleanups to parser

internal/seclang/rule_parser.go, internal/seclang/rule_parser_test.go
Regexes are pretty slow and use memory, forever in the case of package variables. While not terrible, it's good to avoid them where we can I think. In this case there was a combination of regex and cut being used, and an incorrect `3` instead of `2` passed to the regex making the logic even more confusing. Manually writing the code results in much more, but it seems worth it
=> Replace action/operator tokenization from regex to code

internal/corazawaf/rule.go, internal/corazawaf/transaction.go, internal/variables/variables.go, internal/variables/variablesmap.gen.go, rules/transaction.go, types/variables/variables.go
Currently we had the two variables but only one of them was used, given that modsecurity also has INBOUND_DATA_ERROR (see https://github.com/SpiderLabs/ModSecurity/blob/5f632a5ed5cf79fde9dee3ae518631951cee8762/Makefile.am\#L218) it appears that INBOUND_ERROR_DATA was a typo.
Closes #564.
=> breaking: removes INBOUND_ERROR_DATA in favour of INBOUND_DATA_ERROR.

internal/seclang/rule_parser.go
We don't do any unicode handling in the parse so we can loop on bytes without utf8 decoding.
Also don't call `Builder.String()` multiple times to simplify the code (no affect on allocations as that method doesn't allocate, just cleaner IMO)
After
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/seclang
BenchmarkParseActions
BenchmarkParseActions-10    	 1255496	       932.3 ns/op
PASS
```
Before
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/seclang
BenchmarkParseActions
BenchmarkParseActions-10    	 1042354	      1104 ns/op
PASS
```
=> Small cleanups to actions parsing

auditlog/formats.go, auditlog/formats_test.go
We currently seem to print all audit parts or a static set of parts no matter what. This updates the native formatter to only print the requested parts I will also send a separate PR for JSON formatter.
=> Only log requested parts in native formatter

auditlog/concurrent_writer.go, auditlog/concurrent_writer_test.go, auditlog/logger.go, auditlog/noop_writer.go, auditlog/serial_writer.go, auditlog/serial_writer_test.go, internal/seclang/directives.go, internal/seclang/parser.go
I am looking at removing `types.Config` because it is a very implicit type and has awkwardness in using it, with allocations related to defaultValue and `interface{}`. We can use concrete types instead for all our uses as far as I can tell.
This starts by creating an auditlog config type, which needs to be public as its part of the auditlog plugin mechanism. Then it can be removed by adding an internal type for containing parser state/options which is its only other usage right now.
=> Add typesafe auditlog config

internal/seclang/directives.go, internal/seclang/parser.go, internal/seclang/rule_parser.go
Raw rules are stored for audit log purposes. Currently we reconstruct the raw string, but this means that much content of the string is stored twice, in this new string, and as slices from the original parsed line that is often stored in operators such as rx or pm. If we propagate from the original line instead, the string is only present once.
=> Propagate parsed line for raw rule storage

actions/ctl.go, actions/ctl_test.go, internal/corazawaf/rulegroup.go, internal/corazawaf/rulegroup_test.go, internal/seclang/directives.go, internal/seclang/rule_parser.go
It is best to use a slice of structs rather than pointers wherever possible to reduce memory usage a little and improve iteration performance.
This also replaces some find+delete patterns with just delete since they are internal code anyways
=> Cleanup and optimize rulegroup

auditlog/concurrent_writer.go, auditlog/logger.go, auditlog/noop_closer.go, auditlog/serial_writer.go, config.go, config_test.go, internal/corazawaf/transaction.go, internal/corazawaf/waf.go, internal/seclang/directives.go, internal/seclang/directives_log_test.go, internal/seclang/parser.go, testing/auditlog_test.go, waf.go
Audit log is more tricky than debuglog as there are many variables in play: StorageDir, dirMode, fileMode, file. Hence we can do the immutable pattern because that would be overkill.
Closes #698
=> chore: avoids initializing the audit log on every directive.

rules/transaction.go
These methods were only added for us to support content injection which we don't anymore.
=> chore: drops unused methods in TransactionState

internal/actions/setvar.go, internal/actions/setvar_test.go
Setvar wasn't doing many validations, and it was returning panics. Now it only allows TX as we don't support any other mutable variable
=> fix(action): Add many validations for setvar

internal/actions/ctl.go, internal/actions/ctl_test.go, internal/corazawaf/rulegroup.go, internal/corazawaf/rulegroup_test.go, internal/seclang/directives.go, internal/seclang/directives_test.go
Currently ctl:RuleRemoveById and SecRuleRemoveById were focusing in a single value only, however for retrocompatibility with modsec we should accept many values and they can be either ID or range. See:
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29\#user-content-SecRuleRemoveById
- https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v3.x%29\#user-content-ctl
This PR fixes that behaviour and allows this feature to be supported https://github.com/coreruleset/modsecurity-crs-docker/pull/119
Ping @M4tteoP @fzipi
=> fix: adds full support for ruleRemoveById.

testing/coreruleset/.ftw.yml, testing/coreruleset/coreruleset_test.go, testing/coreruleset/go.mod, testing/coreruleset/go.sum
This PR:
- updates tests with the latest CRS commit
- updates go-ftw fixing `920280-1` test
=> chore: updates tests to latest CRS, updates go-ftw

internal/transformations/base64decode.go
I noticed our base64Decode transformation allows mixed content in raw, but that is actually the `base64DecodeExt` transformation AFAICT
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v3.x)#base64decodeext
I think we should go ahead and simplify the implementation of base64Decode for now (CRS tests still pass), and reintroduce the code for implementing base64DecodeExt in the future
=> Use standard library for base64 decode

http/middleware.go, http/middleware_test.go, testing/coreruleset/.ftw.yml
Follows https://github.com/corazawaf/coraza-caddy/issues/53#issuecomment-1500661146 reasoning.
The Go library removes the `Transfer-Encoding` header (see [here](https://github.com/golang/go/blob/master/src/net/http/transfer.go#L631)), therefore rules looking at it are not working.
This PR proposes to read the `TransferEncoding` (part of the http.Request) and populate the header inside Coraza accordingly.
It fixes `920171-2` and `920171-3`.
If it gets merged, I will follow up updating also the caddy connector (it is now sharing the same middleware) to fix https://github.com/corazawaf/coraza-caddy/issues/53.
=> fix: synthesizes Transfer-Encoding header inside the transaction

README.md, http/interceptor.go, internal/operators/pm_from_dataset.go, internal/seclang/directives.go, internal/seclang/rule_parser.go, testing/engine/operators_with_dataset.go
This PR proses to:
- Register `pmFromDataset` operator. It has been added alongside ipMatchFromDataset, the latter is properly registered, but not the first. I guess we just forgot it, I think that it is still a valuable operator.
- Fixes `options.Datasets` propagation: Inside pmFromDataset and ipMatchFromDataset the Datasets slice was always ending to be empty resulting in an error not being able to find the dataset.
- Adds `operators_with_dataset` tests for both pmFromDataset and ipMatchFromDataset.
=> registers pmFromDataset, fixes Dataset propagation, adds tests

README.md, SECURITY.md
- use github reporting instead of email
- update readme with coraza twitter
- mention the process we follow for security disclosures
=> docs: update README and SECURITY

internal/actions/ctl.go, internal/corazawaf/transaction_test.go, internal/seclang/directives.go, types/waf.go
=> Validate audit log parts

internal/corazawaf/rule.go, internal/corazawaf/rule_test.go
PR meant to increase `rule.go` test coverage
=> chore: increases rule.go test coverage

internal/corazarules/rule_match.go
the matchData is called from loop in AuditLog
=> remove wrong loop in matchData

examples/http-server/main.go, http/middleware_test.go, internal/corazarules/rule_match.go, internal/corazarules/rule_match_test.go, internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, internal/seclang/rules_test.go, testing/coreruleset/coreruleset_test.go, testing/engine.go, types/rule_match.go
follows https://github.com/corazawaf/coraza/issues/795 reasonings. Proposes to remove the `code` parameter from `ErrorLog` and `AuditLog`.
=> breaking: removes code parameter from ErrorLog and AuditLog

internal/actions/ctl_test.go, internal/auditlog/formats.go, internal/auditlog/formats_test.go, internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go, internal/seclang/rules_test.go, types/waf.go, types/waf_test.go
according to https://coraza.io/docs/seclang/directives/#secauditlogparts, `A` is mandatory,and should break when reached `Z` 
https://github.com/corazawaf/coraza/issues/678#issuecomment-1565207682
=> fix:force require 'A' in Auditlogparts

README.md
Quite some questions are around CRS `v3.*` support (Like https://github.com/corazawaf/coraza/discussions/817, https://github.com/corazawaf/coraza/discussions/833 and https://github.com/corazawaf/coraza/issues/509). Could it make sense to clearly state that only the `v4` branch is compatible with Coraza?
=> chore(readme): explicits CRS supported version

examples/http-server/go.sum, magefile.go, testing/coreruleset/go.sum
=> chore: adds go mod tidy and go work sync for all modules.

README.md
Follows https://github.com/corazawaf/coraza/pull/841, updates the correct command to run standalone e2e tests
=> chore: updates e2e standalone command

http/e2e/e2e.go
Working on https://github.com/corazawaf/coraza-caddy/pull/96 (e2e is failing I'm trying to update it with the new one), I found that Caddy properly aborts the response if at phase 3 a deny action is triggered. It means that the response body can not be read.
**Caddy Log:**
```
e2e-caddy-1  | {"level":"error","ts":1690387902.7979822,"logger":"http.handlers.waf","msg":"[client \"192.168.176.4\"] Coraza: Access denied (phase 3).  [file \"\"] [line \"10\"] [id \"103\"] [rev \"\"] [msg \"\"] [data \"\"] [severity \"emergency\"] [ver \"\"] [maturity \"0\"] [accuracy \"0\"] [hostname \"\"] [uri \"/response-headers?pass=leak\"] [unique_id \"RkQqgctUauuoQNPt\"]\n"}
e2e-caddy-1  | {"level":"error","ts":1690387902.798008,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete …
```
=> chore(e2e): check response body read error only if a body is expected

go.mod, go.sum, testing/coreruleset/go.mod, testing/coreruleset/go.sum, testing/e2e/e2e_test.go
This is based on latest performance improvements in aho-corasick https://github.com/petar-dambovaliev/aho-corasick/pull/11.
=> chore: upgrades coraza to latest aho-corasick.

README.md, internal/environment/default.go, internal/environment/nofsaccess.go
=> docs: adds no_fs_access build tag to docs.

examples/http-server/go.mod, experimental/plugins/macro/macro.go, go.work.sum, internal/actions/logdata.go, internal/actions/setvar.go, internal/actions/setvar_test.go, internal/corazawaf/rule.go, internal/corazawaf/rule_test.go, internal/corazawaf/transaction.go, internal/corazawaf/waf.go, testing/coreruleset/go.mod, testing/coreruleset/go.sum
This PR:
- simplifies setvar evaluation code, reusing the same variable expansion for both `+` and `-` operations.
- Fixes a bug that was not allowing to initialize a variable with a negative number.
- `setvar:TX.score=+5`: even if `TX.score` does not exist, it defaults to 0 and the variable is initialized to `5`.
- `setvar:TX.score=-5`: was failing. Now, the behavior is aligned. Even if `TX.score` does not exist, it defaults to 0 and the variable is initialized to `-5`.
- Adds a warning when a macro is expanded but the variable is not found in the collection. It notably happens in https://github.com/corazawaf/coraza/issues/888. When variables are used before being initialized (E.g. becuase of a misconfiguration), the macro expansion returns the name of the variable itself. It might lead …
=> chore: setvar minor fix, tests, added warning when missing variable, deprecates usage of tx.LogData

http/interceptor.go, http/interceptor_test.go
--------
Before this change `http.Flusher` and `io.ReaderFrom` essentially acted like a bypass for the coraza middleware because they directly called the underlying writer.
`http.Flusher` is unimplementable because it doesn't make sense to flush early to the client. It does have one observable effect. A call to `Flush` before a call to `Write` (or `WriteHeader`) also implies a call to `WriteHeader`.
`io.ReaderFrom` can be …
=> fix `http.Flusher` and `io.ReaderFrom` implementation

http/interceptor.go, http/interceptor_test.go
------------
https://github.com/corazawaf/coraza/pull/923 introduced a stackoverflow when the value passed to `ReadFrom` does not implement the `io.WriterTo` interface.
From the `go` stdlib source :
```go
// copyBuffer is the actual implementation of Copy and CopyBuffer.
// if buf is nil, one is allocated.
func copyBuffer(dst Writer, src Reader, buf []byte) (written int64, err error) {
// If the reader has a WriteTo method, use it …
```
=> fix: stackoverflow in `ReadFrom`

internal/transformations/base64decode.go, internal/transformations/base64decode_test.go
Sibling of https://github.com/corazawaf/coraza/pull/940, providing a custom implementation of base64 decoding. The same tests are executed.
The implementation is a refactored version of https://github.com/corazawaf/coraza/pull/758 to allow missing padding and decode up to an illegal character.
We have to decide between:
- Rely (hacky) on a the std library transformation (definitely more confident about the implementation)
- Rely on and maintain our custom implementation (faster, less confident about the implementation, no unexpected changes not relying on undocumented std library functions behaviors) 
Benchmarks:
**PR: custom implementation (this PR)**
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/transformations
BenchmarkB64Decode/VGVzdENhc2U=-10 …
```
=> fix: more forgiving base64 transformation [custom implementation]

internal/corazawaf/transaction.go, testing/auditlog_test.go
=> fix: filling variables struct to complete audit info

internal/bodyprocessors/raw.go, internal/bodyprocessors/raw_test.go
Adds the raw body processor discussed in #938.
Example configuration:
```
Secrule REQUEST_HEADERS:Content-Type "@rx ^application/x-www-form-urlencoded" "id:100,phase:1,pass,nolog,noauditlog,ctl:requestBodyProcessor=URLENCODED"
Secrule REQUEST_HEADERS:Content-Type "@rx ^multipart/form-data" "id:101,phase:1,pass,nolog,noauditlog,ctl:requestBodyProcessor=MULTIPART"
Secrule REQUEST_HEADERS:Content-Type "@rx ^application/xml" "id:102,phase:1,pass,nolog,noauditlog,ctl:requestBodyProcessor=XML"
Secrule REQUEST_HEADERS:Content-Type "@rx ^application/json" "id:103,phase:1,pass,nolog,noauditlog,ctl:requestBodyProcessor=JSON"
Secrule REQUEST_HEADERS:Content-Type "@rx ^text/xml" "id:104,phase:1,pass,nolog,noauditlog,ctl:requestBodyProcessor=XML"
SecRule REQBODY_PROCESSOR "!@rx …
```
=> Add raw body processor

http/e2e/cmd/httpe2e/main.go, http/e2e/e2e.go, testing/e2e/e2e_test.go
=> feat: expose expected directives for e2e test

internal/corazawaf/rule.go
Prior to that change, Noop logger would execute `With` function for no benefits.
When running rule evaluation at high scale, the number of memory allocation sky rockets (~300MB / min at 1k RPS). This change proposes to make sure the logger is active before executing costly `With` function.
=> avoid executing costly With if noop logger

http/e2e/e2e.go
To give more context, when trying this e2e suite with traefik and traefik wasn't able to pull the wasm binary then every call would return 404 which I wasn't informed by logs.
=> tests: adds logs for unexpected status code.

internal/corazarules/rule.go, internal/corazawaf/rule.go
While testing the library at 1K RPS, `pprof` showed that this `strconv.Itoa` alone is adding a ~2.2% CPU usage.
Since this ID is per rule and does not change over time, we can compute it once, cache it and reuse.
=> cache Rule ID string version

magefile.go
=> fix: FuzzB64Decode regexp match for fuzzing

internal/seclang/rules_test.go
- fix parameter pollution tests
- they will fail when we add support for case sensitive args and args names
=> fix: http parameter pollution test cases

internal/corazawaf/rule_test.go, internal/corazawaf/transaction.go, testing/engine/multiphase.go
In Multiphase, `ARGS` are split into `ARGS_POST` and `ARGS_GET`. Because of that, a `ruleRemoveTargetById` targeting ARGS, is not working because it adds an exception to a variable that is not checked.
This PR proposes to split ARGS also inside the `ruleRemoveTargetById` adding effectively the two specialized exceptions (one for `ARGS_POST` and one for `ARGS_GET`).
- Fixes an expected behaviour.
- CRS rules [942440, 942441, 942442](https://github.com/coreruleset/coreruleset/blob/4fb2625c37d63428bccc20ebdac6601201b500f8/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1322-L1345) are based on this logic.
=> fix: RemoveTargetById Args in multiphase mode

http/interceptor.go, http/middleware.go, http/middleware_test.go
Initially reported in https://github.com/corazawaf/coraza-caddy/issues/147. We basically use the same Go middleware, therefore I first tried to reproduce and propose an initial patch here.
Port to coraza-caddy is required.
=> fix: headers leaked during interruptions at phase 3/4

internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go
=> chore: deletes content temporary file on close.

examples/http-server/main_test.go, internal/actions/ctl_test.go, internal/actions/id.go, internal/corazarules/rule.go, internal/corazawaf/rule.go, internal/corazawaf/rule_test.go, internal/corazawaf/transaction_test.go, internal/seclang/directives.go, internal/seclang/rule_parser.go, magefile.go
WIP.
Implements `StrID` at rule parsing time in order to fix race conditions introduced by the lazy pattern. It basically creates the variable alongside the `ID` variable creation. 
I'm still unsure about the `StrRuleID_` name. The goal is to explain that it is not always just the string of `ID_`, but it is the "displayed" ID, so for chained rules, the displayed id is the parent id even if the inner rule (being an inner rule) has the `0` value ID.
Fixes https://github.com/corazawaf/coraza/issues/1083
=> fix: race condition on StrID

internal/corazarules/rule_match.go
Logs generated by the [CRS correlation rule `980170`](https://github.com/coreruleset/coreruleset/blob/main/rules/RESPONSE-980-CORRELATION.conf#L77-L100) is quite lengthy and the current fixed max size of msg logs leads to don't print it fully.
Example of truncated log:
```
[msg "Anomaly Scores: (Inbound Scores: blocking=15, detection=15, per_pl=15-0-0-0, threshold=5) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=4) - (SQLI=0, XSS=15, RFI=0, LFI=0, RCE"] [data ""]
```
While a max value is advisable, it should still permit to fit the output of known rules. This PR proposes to increase the `maxSizeLogMessage` from `200` to `280` in order to print something like:
```
Anomaly Scores: (Inbound Scores: blocking=15, detection=15, per_pl=150-250-150-150, threshold=1000) - …
```
=> fix: makes max size log message CRS correlation rule friendly

internal/seclang/rule_parser.go, internal/seclang/rule_parser_test.go
Fixed the issue that the ParseVariables function would parse the regular expression with escape characters incorrectly
fix #1088
=> fix: variable parsing error 

internal/actions/deny.go, testing/engine/disruptive_actions.go
This PR proposes to set `403` as default deny status code instead of delegating it to the connectors. 
If the rule `status` field is not set, `Deny` action is currently setting the status code of the interruption equal to `0`. Only at the connector level, there is some logic to convert the `0` into a `403`. Example in [coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm/blob/de6279b086d2cb3f1e7df7a88d73b2837feeb2b4/wasmplugin/plugin.go#L699-L703):
```
statusCode := interruption.Status
if statusCode == 0 {
statusCode = defaultInterruptionStatusCode
}
if err := proxywasm.SendHttpResponse(uint32(statusCode), nil, nil, noGRPCStream); err != nil {
```
Delegating it to the connector leads to `SecAuditLogRelevantStatus` not working properly. The regex `^(?:(5|4)(0|1)[0-9])$` tries …
=> fix: deny action with default status 403

coraza.conf-recommended, experimental/plugins/plugintypes/transaction.go, internal/bodyprocessors/multipart.go, internal/bodyprocessors/multipart_test.go, internal/corazawaf/transaction.go, testing/coreruleset/go.mod, testing/coreruleset/go.sum, types/variables/variables.go
- set MULTIPART_STRICT_ERROR as it is used in coraza.conf-recommended but never set
- as the parser doesn't implement all the sub-variables from modsecurity, at least a global failure must be propagated
- to catch possible evasion attempts with multipart data
=> feat: set MULTIPART_STRICT_ERROR value when mutipart fails to parse

renovate.json
- prevent renovate to go beyond our golang supported version
- use best-practices instead of recommended
- do not waste time reverting renovatebot changes in major release
- get best-practices
=> chore:  config renovate to update up to our supported go version

README.md
Basically it aligns the README page to the Introduction page of our site adding changes done via https://github.com/corazawaf/coraza.io/pull/251.
Resolves https://github.com/corazawaf/coraza/discussions/1090
=> chore(README): removes mention to EOL of Modsec

internal/operators/inspect_file_test.go
This is a small for TestInspectFile on windows. As windows is not able to run /bin/echo I choose an alternative for this platform.
Why tasklist.exe?
- it is available on all windows versions
- it is available on wine
- it does not require elevated privileges
I also changed the argument from "" to "/?" to ensure that tasklist.exe does not do anything. On *nix this does not have any impact.
Why not XYZ?
I was unable to find a suitable platform independent alternative, as "finding" an available binary (e.g. go) at runtime would make the test more complex than the actual code.
=> fix: broken TestInspectFile on windows

internal/bodyprocessors/multipart.go
The multipartBodyProcessor is broken on windows, because it creates a temporary file without closing it.
This would usually not be a problem, as the gc would take care of it, but the tests on windows fail, because go test tries to delete the files before gc cleaned the file descriptors.
Windows refuses to delete files as long as the file descriptor is open. Closing the temporary file fixes this issue and go test is able to cleanup the files.
=> fix: broken multipart processor on windows

internal/seclang/directives_test.go
This is a small fix for the SecUploadDir directive test. On windows /tmp does not exist, so I choose a platform independent approach. This test now passes OK on windows and *nix.
=> fix: broken TestDirectives SecUploadDir on windows

internal/auditlog/concurrent_writer_test.go
This is a small fix for TestConcurrentWriterSuccess on windows.
Windows refuses to delete files as long as the file descriptor is open. Closing the temporary file and the concurrentWriter log files fixes this issue and go test is able to cleanup the files.
=> fix: broken TestConcurrentWriterSuccess on windows

.github/workflows/tinygo.yml
- updates tinygo to 0.33.0
- compatible with go 1.23
- https://github.com/tinygo-org/tinygo/releases/tag/v0.33.0
=> chore: update tinygo to 0.33.0

experimental/plugins/macro/macro_test.go, internal/actions/setvar_test.go
Adding a missing test based on the macro expansion for an unknown key.
Related: https://github.com/corazawaf/coraza/pull/1125
=> tests: unknown key.

internal/corazawaf/rule.go, internal/corazawaf/rulegroup.go
---
Closes https://github.com/corazawaf/coraza/issues/1147.
The Godoc of `reflect.StringHeader` states [^1]:
> the Data field is not sufficient to guarantee the data it references will not be garbage collected, so programs must keep a separate, correctly typed pointer to the underlying data.
And the Godoc of `unsafe.Pointer` states [^2]:
> (2) Conversion of a Pointer to a uintptr (but not back …
=> refactor: replace `reflect.StringHeader` with `unsafe.StringData`

experimental/plugins/macro/macro.go, experimental/plugins/macro/macro_test.go
- fix macro parsing to handle additional border cases
- Fix #1178.
=> fix: handle additional broken macro definitions

internal/actions/redirect.go, testing/engine/disruptive_actions.go
- `redirect` action should by default redirect using code 302
- if `status` action exists, with some specific 3xx codes, then use those
- `redirect` action is not working as the documentation states
=> fix: redirect action status codes

renovate.json
- use centralized renovatebot config
- standarization
- easier maintenance
=> chore: update renovate config to use common

examples/http-server/go.mod
- fix toolchain version
- As of Go 1.21, toolchain versions [must use the 1.N.P syntax](https://go.dev/doc/toolchain#version).
=> fix: toolchain version in go.mod

internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go
One less alloc/op, but numbers can matter at scale.
Before:
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/corazawaf
cpu: Apple M1 Pro
BenchmarkTxGetField-10    	 2294287	       582.5 ns/op	     448 B/op	       9 allocs/op
PASS
ok  	github.com/corazawaf/coraza/v3/internal/corazawaf	2.374s
BenchmarkCRSSimplePOST-10    	     902	   1276337 ns/op	  338771 B/op	    7220 allocs/op
PASS
ok  	github.com/corazawaf/coraza/v3/testing/coreruleset	2.054s
```
After:
```
goos: darwin
goarch: arm64
pkg: github.com/corazawaf/coraza/v3/internal/corazawaf
cpu: Apple M1 Pro
BenchmarkTxGetField-10    	 3306369	       355.6 ns/op	     400 B/op	       8 allocs/op
PASS
ok  	github.com/corazawaf/coraza/v3/internal/corazawaf	2.051s
BenchmarkCRSSimplePOST-10    	     874	   1262635 …
```
=> perf: GetField reduce allocations

.github/workflows/regression.yml
=> add codecov token

README.md, internal/operators/multilineregex.go, internal/operators/multilineregex_default.go, internal/operators/rx.go, internal/operators/rx_no_multiline_test.go, internal/operators/rx_test.go, magefile.go
This PR evaluates the needed changes to align Coraza to Modsec v2 behavior rather than Modsec v3 in terms of default modifiers when compiling regexes. This necessity has been raised by https://github.com/coreruleset/coreruleset/issues/3277. 
We are currently running with two default modifiers: 
- s (dotall)
- m (multiline mode)
While Modsec v2 (the reference implementation for the CRS) has:
- PCRE2_DOTALL
- PCRE2_DOLLAR_ENDONLY
Running the CRS rules with multiline may lead to false positives and lower performance.
Opening the PR to further discuss this, and whether we accept a breaking change for `v3.*` or not.
EDIT: The change has been implemented under the `coraza.rule.no_regex_multiline` build flag and is disabled by default.
=> fix: removes multiline from default regex modifiers

experimental/plugins/macro/macro.go, experimental/plugins/macro/macro_test.go
**Summary**
This update allows square brackets (`[]`) in variable names, enabling compatibility with parameters like `ARGS.db-reset-tables[]`. Previously, these would result in errors, limiting Coraza's ability to handle some ModSecurity rule sets.
**Why This Matters?**
Square brackets are widely used in GET parameters and filenames. For example:
- PHP use them for array-like parameters (e.g., …
=> Allow square brackets in variables (macro expansion)

internal/corazawaf/transaction.go, internal/corazawaf/transaction_test.go
Follows https://github.com/corazawaf/coraza/pull/1223
This PR adds a benchmark and also optimization for time variables
**Before**
```
BenchmarkTransactionTimestamped-12       6194395           165.1 ns/op        16 B/op          2 allocs/op
```
**After**
```
BenchmarkTransactionTimestamped-12      12029612            99.59 ns/op       16 B/op          2 allocs/op
```
cc @geoolekom
=> chore: optimizes time variables.

internal/transformations/base64encode.go, internal/transformations/transformations.go
This PR brings [base64Encode](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-(v3.x)#user-content-base64Encode) method.
[Issue 1252](https://github.com/corazawaf/coraza/issues/1252)
This changes rely on `encoding/base` std library  `base64.StdEncoding.EncodeToString`
I spent a little bit of time to investigate if it's necessary to implement custom base64Encode. If you have any doubts, real cases where std doesn't work or not appropriate for this project, please let me know here. …
=> feat: add base64 encode transformation

internal/seclang/parser.go, internal/seclang/parser_test.go
Implements https://github.com/corazawaf/coraza/issues/1250.
This PR adds an "empty glob" error when trying to include files using a glob pattern, but the pattern does not match any file.
If a user specifies a config file with `Include rules./*.conf`, the intent is that a number of files will be parsed (at least 1 :sweat_smile:). 
If for some reason the glob pattern does not match any file, we should return an error so that the user realizes there is a problem with the configuration. 
The user can then fix the glob pattern (or remove it if not needed), instead of assuming that the expected configuration files have been loaded. 
- [x I have read [Contribution guidelines](https://github.com/corazawaf/coraza/blob/master/CONTRIBUTING.md#contribution-guidelines), [maintainers …
=> fix: add empty glob error when no files match

internal/corazawaf/rule.go, internal/corazawaf/rule_test.go
=> Revert "chore: Replace sync.Mutex with sync.Map"

internal/seclang/parser.go, internal/seclang/parser_test.go
Despite https://github.com/corazawaf/coraza/pull/1259 being the right thing from user experience, it was a breaking change, hence turning into a warning to not to break existing behaviour.
Fixes #1280 cc @nimasamii
=> fix: warn instead of returning error on empty glob result (#1280)

.github/workflows/regression.yml
- adds a new job in regression tests to prevent PRs to be merged unless everything has been a `success` in the pipeline
- fix deprecation in `set-output`
- we must reassure that tests pass for all combinations
=> ci: add wait-for-status check

magefile.go
Fixes https://github.com/corazawaf/coraza/issues/1329.
Bumps the linter to a version (latest) that supports Go `1.24`.
=> fix(go1.24): bump linter

README.md
Hey folks!
While using Coraza, I discovered a pain point: although Coraza is an incredibly powerful WAF engine, it lacks an intuitive management panel and some practical traffic control strategies. As a practitioner, I felt these features are quite important for daily operations.
So I rolled up my sleeves and built some extensions based on coraza-spoa, creating the [RuiQi WAF](https://github.com/HUAHUAI23/RuiQi) project. Key features include:
🎛️ Web Management Panel - Provides intuitive rule management, log viewing, and configuration interface
🚦 Traffic Control Policies - Supports rate limiting, blacklists/whitelists, and other flow control features
🔧 Micro-engine Extensions - Enhances usability while maintaining Coraza's core capabilities
📊 Monitoring & Analytics - Real-time traffic …
=> docs: add RuiQi to integrations list

http/middleware.go, http/middleware_test.go
Reverts corazawaf/coraza#1345
After deeper consideration, this approach only allows to have tx access up to phase 2 if it isn't interrupted which is nothing useful. I am convinced now the right approach is to provide hooks that users can implement and get more useful access without compromising the tx lifecycle.
=> Revert "chore: add tx to context"

examples/http-server/main_test.go, internal/corazawaf/transaction.go, internal/seclang/directives.go
Closes #1377 
- Improved documentation
- Fixed Status code in response case, now 500 is returned
=> fix: wrong status returned when SecResponseBodyLimit is reached and Action is Reject

internal/seclang/rule_parser.go, internal/seclang/rule_parser_test.go
When a escaped double quotes (`\"`)  is followed by a non escaped double quotes (`"`), the non escaped double quotes (`"`) was not properly identified because there was a missing reset to escape count.
=> fix: cutQuotedString - not working for `\""`
